name = "karaokeq"
main = "src/index.ts"
compatibility_date = "2022-09-10"

[[kv_namespaces]]
  binding = "KARAOKEQ"
  id = "b21515f834af4f55a728a5465cbcc471"
  preview_id = "b21515f834af4f55a728a5465cbcc471"
  
[durable_objects]
  bindings = [{ name = "KARAOKEQ_DB", class_name = "Db" }]

[[migrations]]
  tag = "v1"
  new_classes = ["Db"]