export function getRandomName(seedStr: string) {
  const seed = cyrb128(seedStr)
  var rand = sfc32(seed[0], seed[1], seed[2], seed[3])
  return randomNames[Math.floor(rand() * randomNames.length)]
}

/*
I want anonymous users on my platform to feel a little more personal. Therefore i want to generate random 'anonymous <something>' names for them that are cute and funny and quirky.
1000 unique such names are:
<names>
...
*/
const randomNames = [
  "Badger",
  "Cookie",
  "Tomato",
  "Hedgehog",
  "Butterfly",
  "Blueberry",
  "Kiwi",
  "Flamingo",
  "Cupcake",
  "Jellybean",
  "Penguin",
  "Unicorn",
  "Rainbow",
  "Muffin",
  "Popsicle",
  "Peanut",
  "Koala",
  "Potato",
  "Sprinkles",
  "Pancake",
  "Marshmallow",
  "Sloth",
  "Donut",
  "Walrus",
  "Moonbeam",
  "Watermelon",
  "Gummybear",
  "Polarbear",
  "Bunny",
  "Snickerdoodle",
  "Cherub",
  "Tweety",
  "Daisy",
  "Popcorn",
  "Sunflower",
  "Blossom",
  "Chickadee",
  "Sushi",
  "Raindrop",
  "Sparkle",
  "Honeybee",
  "Plum",
  "Sunrise",
  "Lavender",
  "Quokka",
  "Pebbles",
  "Dream",
  "Panda",
  "Firefly",
  "Smiley",
  "Giraffe",
  "Biscuit",
  "Banana",
  "Robin",
  "Quicksilver",
  "Minty",
  "Caramel",
  "Lemonade",
  "Bubblegum",
  "Teacup",
  "Goldilocks",
  "Peppermint",
  "Meerkat",
  "Macaroon",
  "Glitter",
  "Nebula",
  "Mango",
  "Gazelle",
  "Buttercup",
  "Squishy",
  "Twilight",
  "Pineapple",
  "Kiwifruit",
  "Wombat",
  "Starfish",
  "Grapefruit",
  "Zucchini",
  "Kangaroo",
  "Moonlight",
  "Rosebud",
  "Hibiscus",
  "Dandelion",
  "Dragonfly",
  "Dumpling",
  "Mushroom",
  "Whale",
  "Apricot",
  "Mantis",
  "Peacock",
  "Cherry",
  "Peony",
  "Cornflower",
  "Brownie",
  "Guava",
  "Starlet",
  "Pumpkin",
  "Apple",
  "Lily",
  "Hummus",
  "Ladybug",
  "Mimosa",
  "Pretzel",
  "Oasis",
  "Sunbeam",
  "Candyfloss",
  "Sundae",
  "Olive",
  "Strawberry",
  "Peapod",
  "Turtle",
  "Honeydew",
  "Magnolia",
  "Bagel",
  "Almond",
  "Lemur",
  "Icicle",
  "Angel",
  "Ferret",
  "Lemongrass",
  "Jaguar",
  "Pixie",
  "Lollipop",
  "Cantaloupe",
  "Firecracker",
  "Spaghetti",
  "Tangerine",
  "Hazelnut",
  "Nutmeg",
  "Sunshine",
  "Celery",
  "Pomegranate",
  "Waffles",
  "Gingerbread",
  "Joy",
  "Pistachio",
  "Zephyr",
  "Kiwibird",
  "Kitten",
  "Dolphin",
  "Papaya",
  "Cucumber",
  "Maple",
  "Snowflake",
  "Tulip",
  "Hummingbird",
  "Grasshopper",
  "Chameleon",
  "Taco",
  "Macaw",
  "Gopher",
  "Waterfall",
  "Sapphire",
  "Almighty",
  "Cordial",
  "Gerbil",
  "Galaxy",
  "Noodle",
  "Sugarplum",
  "Huckleberry",
  "Porcupine",
  "Salamander",
  "Tiger",
  "Chinchilla",
  "Mandarin",
  "Raccoon",
  "Kumquat",
  "Mongoose",
  "Tiramisu",
  "Mockingbird",
  "Elephant",
  "Polaris",
  "Peach",
  "Parrot",
  "Coconut",
  "Cocoa",
  "Emerald",
  "Cheetah",
  "Marsh",
  "Cinnamon",
  "Seashore",
  "Daffodil",
  "Cricket",
  "Moonstone",
  "Kookaburra",
  "Eel",
  "Poppy",
  "Bamboo",
  "Ants",
  "Weasel",
  "Angelcake",
  "Avocado",
  "Pinecone",
  "Narwhal",
  "Bluejay",
  "Ivy",
  "Piranha",
  "Potpie",
  "Porpoise",
  "Lava",
  "Nougat",
  "Capuchin",
  "Swan",
  "Starburst",
  "Chipmunk",
  "Jellyfish",
  "Sunray",
  "Mouflon",
  "Orca",
  "Moose",
  "Ellipses",
  "Quasar",
  "Rhubarb",
  "Sherbet",
  "Tumbleweed",
  "Toucan",
  "Yak",
  "Zebra",
  "Wolverine",
  "Xerus",
  "Pizza",
  "Quoll",
  "Octopus",
  "Iguanodon",
  "Lizard",
  "Jellyroll",
  "Kale",
  "Melon",
  "Caramelito",
  "Chimichanga",
  "Fruitcake",
  "Carnation",
  "Cornflakes",
  "Daffodils",
  "Fluffybun",
  "Jujubes",
  "Lilybell",
  "Mistergreeky",
  "Nutbark",
  "Pancapuff",
  "Treacletoffee",
  "Waterfallspark",
  "Yumbunnies",
  "Ziptopic",
  "Tenderhonky",
  "Prettychimp",
  "Elegantloon",
  "Ghosthound",
  "Icecreamdimples",
  "Luckyfluffer",
  "Sumptuousmeatball",
  "Yellowyeti",
  "Ziplinezebra",
  "Antelopeapple",
  "Vanilla Vlamingo",
  "Whiskyroo",
  "Vermin Violet",
  "Frostfloe",
  "Fizzfox",
  "Figfinker",
  "Thundercube",
  "Squeaksprinkle",
  "Rushcrows",
  "Partygizzard",
  "Offcross",
  "Jellyhipo",
  "Frizzenhawk",
  "Opalesce",
  "Obsquaddle",
  "Dragonteddy",
  "Biscuit Beetle",
  "Spicy Sneasel",
  "Frosted Flakes",
  "Flour Flea",
  "Artistic Amaryllis",
  "Adorable Articuno",
  "Inky Izze",
  "Soulful Shelter",
  "Mezzo Pelatti",
  "Topsy Cortado",
  "Humpty Fruitsalad",
  "High Babka",
  "Spidling Sparkling",
  "Velvet Pinoli",
  "Cute Plushowl",
  "Audacious Peache",
  "Snowy Coconut",
  "Craving Tortilla",
  "Lovingcashew",
  "Dancing Custard",
  "Twinkly Tortoise",
  "Sparking Radish",
  "Ginger Typhoon",
  "Humming Mint Loaf",
  "Bashful Bonito",
  "Apple Anemone",
  "Subtle Paan",
  "Fantasy Marzipan",
  "Tender Chiyya",
  "Yankee Pudding",
  "Captain Woopie Peach Pie",
  "Escaping Meizi",
  "Sassy Longan",
  "Sundae Shipwrecker",
  "Maraschino Dreams",
  "Crying Yaluoo",
  "Stalky Shrove…",
  "Phantom Parwal",
  "Gabbing Gambooge",
  "Grand Pidan",
  "Lustworthy Kabacus",
  "Hungry Ugliar",
  "Snacking Spoonhunter",
  "Mucking Khaya Nuts",
  "Bashlful Sagopalm Pincone",
  "Peaceful Peas",
  "Lily Hunter",
  "Ginger Ninja",
  "Galloping Grape",
  "Boozy Blackberry",
  "Dopey Cranberry",
  "Singalore Chilli",
  "Taco Destroyer",
  "Orangatang Pesto",
  "Orangutan Oranges",
  "Kangaroo Curry",
  "Butyllon Babymoon",
  "Kalmkuco Khazd",
  "Yam Yucca",
  "Tarro Tearagate",
  "Penny Pebblecake",
  "Supermoon Stardust",
  "Marchmallow Muffler",
  "Ruby Rocket",
  "Lululime",
  "Cool Cucumberlight",
  "Kraving Kiwipunch",
  "Babbling Bamboo",
  "Macchiato Moorhen",
  "Hlazy Hibiscusbee",
  "Peristeronic Poppypie",
  "Quasar Quenepa",
  "Owl Orientapple",
  "Captain Catnip",
  "Kickass Kuromamekwaii",
  "Crazed Cocoa",
  "Mezze Mahonia",
  "Rusty Raisincookie",
  "Octoline Orionstar",
  "Acorn Agneau",
  "Nomadic Nachos",
  "Nightinghale Nugget",
  "Melodious Muntries",
  "Zingo Zenzerocake",
  "Saucy Sweetpotato",
  "Lamp Luminara",
  "Periwinkle Pancake",
  "Icebreaker Imlikart",
  "Kiwi Kavander",
  "Profitsquirrel Pokey",
  "Hoppy Hopscotchstella",
  "Booming Bumblebeery",
  "Colorful Candyblow",
  "Thundrebuns",
  "Crispy Cloudberry",
  "Jellyroom Jasmino",
  "Spararchy Sparrow",
  "Prancing Pandasty",
  "Sangily Seagrape",
  "Tipsy Trasberry",
  "Hasta Haricot",
  "Goosling Donutdozzy",
  "Ghostipe",
  "Rafando Radinady",
  "Runny Rosehill",
  "Juicethimo",
  "Cactnu Cryphone",
  "Sunday Hamdeer",
  "Picoseastars",
  "Meiwish Crillfraid",
  "Mangocake Magnophyx",
  "Digioto Doelraita",
  "Mini Lemonstein",
  "Great Danishlades",
  "Chipotle Chinchilla",
  "Cumin Koala",
  "Sizzling Salamander",
  "Windy Whisker",
  "Caramel Corn",
  "Confetti Cone",
  "Hummingbird Honey",
  "Twilight Turtle",
  "Sugarcone Squirrel",
  "Raspberry Raccoon",
  "Firefly Fondue",
  "Coconut Kangaroo",
  "Galactic Kiwi",
  "Climbing Kiwano",
  "Paddling Pineapple",
  "Rainbow On Rice",
  "Whispering Waffle",
  "Crumbling Cookie",
  "Floating Fluffy Puff",
  "Sauntering Sweetpotato",
  "Puttering Pastry",
  "Bobbing Balloon",
  "Fumbling Fox",
  "Cosmic Cranberry",
  "Fiddlestick Fig",
  "Moonglow Mango",
  "Sea-surf Cider",
  "Hazel Nut-nibbler",
  "Carefree Cactus Fruit",
  "Sweet Sparkling Star",
  "Oceanfloating Octopus",
  "Dainty Delight Doughnut",
  "Enchanted Elf-like Eclair",
  "Sea-salted Cherry",
  "Merlot Minnow",
  "Pearly Peas",
  "Spirited Spearmint",
  "Sweetpotato",
  "Rainbowstripes",
  "Nachocosmic",
  "Frostedfremesess",
  "Multibus Mystery",
  "Elegant Elephants",
  "Joyous Jackfruit",
  "Softshell Squirrella",
  "Canoodle Camel",
  "Zany Zorillo",
  "Harmonous Habaneros",
  "Milkyweedy Magathonshell",
  "Cloudcreekercheeks",
  "Jellyjamming Rhino",
  "Tallbread Tartweed",
  "Feelternusch Flowergate",
  "Humorous Hammmerckler",
  "Mulltlivid Mysterreka",
  "Marshflake Monkeyark",
  "Hidden Haybus Jackonda",
  "Elmoooogle Elvisoska",
  "Pillure Pressure Perfect",
  "Chestcherry Kickstable",
  "Typhoon Trentopper",
  "Saturn Scarecondea Shellphase",
  "Magic Moto Applespixies",
  "Dreamcatchome Drairealsugarinkankaônane",
  'Energy Upgruppe "Oolangment Exosseek"',
  "Wowie Zombiequasa Prettsearch-noodle",
  "Starryshell Spachanca Crystcheckpostmelonshell -Raindstpullion+",
  "Punchd Passion Peachringdasher-Inthebanana",
  "Duck Delbit Dixiesecokarareanonymous Maykosatto Lamuka",
]

function cyrb128(str: string): [number,number,number,number] {
  let h1 = 1779033703, h2 = 3144134277,
      h3 = 1013904242, h4 = 2773480762;
  for (let i = 0, k; i < str.length; i++) {
      k = str.charCodeAt(i);
      h1 = h2 ^ Math.imul(h1 ^ k, 597399067);
      h2 = h3 ^ Math.imul(h2 ^ k, 2869860233);
      h3 = h4 ^ Math.imul(h3 ^ k, 951274213);
      h4 = h1 ^ Math.imul(h4 ^ k, 2716044179);
  }
  h1 = Math.imul(h3 ^ (h1 >>> 18), 597399067);
  h2 = Math.imul(h4 ^ (h2 >>> 22), 2869860233);
  h3 = Math.imul(h1 ^ (h3 >>> 17), 951274213);
  h4 = Math.imul(h2 ^ (h4 >>> 19), 2716044179);
  h1 ^= (h2 ^ h3 ^ h4), h2 ^= h1, h3 ^= h1, h4 ^= h1;
  return [h1>>>0, h2>>>0, h3>>>0, h4>>>0];
}

function sfc32(a: number, b: number, c: number, d: number) {
  return function() {
    a >>>= 0; b >>>= 0; c >>>= 0; d >>>= 0; 
    var t = (a + b) | 0;
    a = b ^ b >>> 9;
    b = c + (c << 3) | 0;
    c = (c << 21 | c >>> 11);
    d = d + 1 | 0;
    t = t + d | 0;
    c = c + t | 0;
    return (t >>> 0) / 4294967296;
  }
}